# .github/workflows/main.yml

name: CI - Build and Push Docker Image

# Run this workflow on every push to the 'main' branch
on:
  push:
    branches: ['main']

jobs:
  build_and_push:
    runs-on: ubuntu-latest # Use a standard Linux runner

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Use the current directory for the build
          file: ./Dockerfile # The Dockerfile we created
          push: true # Push the image to Docker Hub
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/algoscope-app:latest # Tag it as 'bimbok/algoscope-app:latest'
